allow_network: false
firerunner_path: "firerunner"
kernel_path: "vmlinux-4.20.0"
runtimefs_dir: "./"
appfs_dir: "output/"
functions:
  sys_gate:
    vcpus: 1
    memory: 128
    runtimefs: "python3.ext4"
    appfs: "sys_gate.img"
    concurrency_limit: 100
  start_assignment:
    vcpus: 1
    memory: 128
    runtimefs: "python3.ext4"
    appfs: "start_assignment.img"
    concurrency_limit: 100
